#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Nov 29 10:00:54 CET 2024
maven-metadata-oss.sonatype.org-snapshot.xml.error=
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata es.tid.netphony\:network-protocols\:1.4.1-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [oss.sonatype.org-snapshot (http\://oss.sonatype.org/content/repositories/snapshots, default, snapshots)]
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1732022225230
maven-metadata-oss.sonatype.org-snapshot.xml.lastUpdated=1732870854609
